# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20171104_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('honors', models.CharField(blank=True, choices=[('s', 'Summa Cum Laude'), ('m', 'Magna Cum Laude'), ('c', 'Cum Laude')], max_length=1)),
                ('gpa', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('classes', models.ManyToManyField(to='resume.Course')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['-start_date', '-end_date'],
            },
        ),
    ]
