# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_course_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='objective',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
