# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20171105_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(max_length=3000)),
                ('date_sent', models.DateField(blank=True, default=datetime.date(2017, 11, 5))),
            ],
        ),
    ]
